services:
  - type: web
    name: easyjobfind-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: FT_CLIENT_ID
        sync: false
      - key: FT_CLIENT_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
